# Generated by Django 5.2.6 on 2025-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=50)),
                ('leader_position', models.CharField(max_length=50)),
                ('leader_photo', models.ImageField(blank=True, null=True, upload_to='leadership_photos/')),
                ('leader_caption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
